### PR TITLE
Target .net standard 1.3 with BitmapFont

### PR DESCRIPTION
**Pull request by Tom94**
The Cyotek.Drawing.BitmapFont project now targets .net standard 1.3 alongside .net framework 2.0 by using the CoreCompat drop-in replacement for System.Drawing. This is useful for cross-platform development.

In order to accomplish this I needed to re-create the BitmapFont csproj file according to the new format while migrating all the options to the best of my ability.

### CODE REVIEW

**Comment by Tom94** [comment]
At https://github.com/ppy/osu-framework we plan to target .net standard for cross-platform and mobile support. For this, we require all dependencies (such as this project) to also target .net standard. I believe the changes in this PR should not impact existing usage scenarios on .net framework 2.0.

**Comment by cyotek** [comment]
Tom,

Thanks for the PR! This was on my list of things to do, but I got sidetracked, not to mention issues I was having with a .NET core project and creating packages with tokenised nuspec files (I don't want version numbers hardcoded in multiple places as clearly at somepoint I'll forgot to update them!)

I tested the PR locally. The first comment I have is the removable of `AssemblyInfo.cs` has inadvertently gotten rid of the `CLSCompliantAttribute` entry - I usually like to set this on libraries as it indicates that the classes don't make public use of non-standard types such as unsigned values.

The storing of the package values directly in the project file shows that the version numbers are hardcoded which is ideally something I wish not to happen (especially when buried in a file you wouldn't normally edit). But I haven't got a suggestion here as I've only done one .NET Core project so far and it took a lot of dancing around before getting nuget to create the package so I've got more learning to do there. (I (probably) can't use the "create package on compile" functionality as I need to digitally sign the library)

Apart from those issues it seems fine - the few limited tests available in the master branch pass and the sample program runs fine. I haven't tested the PR in the other branches which include more tests and support for the binary BMFont format though.

Unsurprisingly the build script is completely broken too, but that's something I'll need to fix.

Regards;
Richard Moss

**Comment by Tom94** [comment]
Hi Richard,

thanks for the quick reply! I just found that the generation of the AssemblyInfo from project settings is only optional in .net standard. The latest commit removes this automatic generation and uses the original AssemblyInfo.cs file again (including `CLSCompliantAttribute`).

I also looked into doing something similar for the nuspec file, but didn't find anything useful yet. I am also very new to .net standard projects---in fact, this port is my first one---and therefore there is a good chance I overlooked something that would help here.

In any case, please let me know if there is something else that needs adjustment in this PR.

Best,
Thomas

**Comment by cyotek** [comment]
Hello,

Once again, many thanks for the PR. This has now been merged - I also added targets for the rest of the normal frameworks given how easy the new project format makes it compared to VS2015 and below.

I've also fixed the build command so it generates packages. Still haven't figured out how to make nuget work properly with the new project files, nuget2 can't read them, nuget4 completely borks the paths and gives error such as "can't find file bin\debug\LibName\bin\debug", so I'm having to hardcode everything. Sigh.

With this out the way I suppose I should merge the extra tests and binary format support to trunk too!

Regards;
Richard Moss

**Pull request merged**
